name: Run Postman Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configuração do Node.js (SEM cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Removido: cache: 'npm' (não necessário para instalação global)

      # 3. Instalação do Newman globalmente
      - name: Install Newman
        run: npm install -g newman

      # 4. Verificação da coleção Postman
      - name: Verify Postman collection
        run: |
          echo "Conteúdo do diretório .postman:"
          ls -la .postman/
          [ -f ".postman/Demo.postman_collection.json" ] || { echo "❌ Arquivo da coleção não encontrado!"; exit 1; }

      # 5. Execução dos testes
      - name: Run Postman tests
        run: |
          newman run .postman/Demo.postman_collection.json \
          --insecure \
          --reporters cli,html \
          --reporter-html-export newman-report.html

      # 6. Upload do relatório
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html