name: Run Postman Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests (continue on failure)
        id: newman-run
        run: |
          newman run .postman/Demo.postman_collection.json \
          --insecure \
          --reporters cli,html \
          --reporter-html-export newman-report.html \
          --working-dir $GITHUB_WORKSPACE
          --suppress-exit-code || echo "⚠️ Testes falharam, mas relatório foi gerado"
          

      - name: Upload HTML report (always)
        if: always()  # Executa mesmo se o passo anterior falhar
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html