name: Run Postman Tests with Newman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configuração do Node.js (com cache para instalação mais rápida)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Instalação do Newman globalmente
      - name: Install Newman
        run: npm install -g newman

      # 4. Verificação se a coleção Postman existe
      - name: Verify Postman collection
        run: |
          echo "Conteúdo do diretório .postman:"
          ls -la .postman/
          if [ ! -f ".postman/Demo.postman_collection.json" ]; then
            echo "❌ Arquivo da coleção não encontrado!"
            exit 1
          fi

      # 5. Execução dos testes com Newman
      - name: Run Postman tests
        run: |
          newman run .postman/Demo.postman_collection.json \
          --insecure \
          --reporters cli,html \
          --reporter-html-export newman-report.html \
          --working-dir .postman/

      # 6. Upload do relatório HTML como artefato
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman-report.html
          retention-days: 5  # Opcional: define tempo de retenção do artefato

      # 7. (Opcional) Exibe o resumo no log
      - name: Show test summary
        run: |
          echo "✅ Testes Postman concluídos!"
          echo "Relatório disponível como artefato: newman-html-report"